from . import config

_T = config.Primary
_M = config.Tertiary
_B = config.Secondary
_G = config.Muted
_R = config.Reset

ONLINE_HELP = {
    "play": [
        f"{_T}> play{_R} {_M}<query | index | liked>{_R}",
        f"{_G}  Search and play a song from YouTube.{_R}",
        f"  {_M}<query>{_R}   {_G}Search YouTube and play the top result{_R}",
        f"  {_M}<index>{_R}   {_G}Play a song by index from last search results{_R}",
        f"  {_M}liked{_R}     {_G}Play all liked songs{_R}",
        f"  {_M}Flags:{_R} {_G}{_M}-bg{_R} {_G}background |{_R} {_M}-r{_R} {_G}repeat |{_R} {_M}-s{_R} {_G}shuffle |{_R} {_M}-d{_R} {_G}download{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}play never gonna give you up{_R}",
        f"    {_G}play 3{_R}",
        f"    {_G}play liked{_R} {_M}-s{_R}",
        f"    {_G}play never gonna{_R} {_M}-d{_R}",
    ],
    "search": [
        f"{_T}> search{_R} {_M}<query>{_R}",
        f"{_G}  Search YouTube for tracks. Lists results with indices.{_R}",
        f"{_G}  Use the index with {_M}'play <index>' {_G}to play a specific result.{_R}",
        f"  {_G}Example:{_R}",
        f"    {_G}search daft punk{_R}",
    ],
    "like": [
        f"{_T}> like{_R}",
        f"{_G}  Like/unlike the currently playing song.{_R}",
        f"{_G}  Liked songs are saved to {_M}~/.flow/library.json{_R}",
        f"{_G}  Use {_M}'play liked'{_G} to play all liked songs.{_R}",
    ],
    "download": [
        f"{_T}> download{_R} {_M}<query | index>{_R} {_M}[-f format]{_R}",
        f"{_G}  Download audio from YouTube without playing.{_R}",
        f"  {_M}<query>{_R}   {_G}Search and download the top result{_R}",
        f"  {_M}<index>{_R}   {_G}Download by index from last search results{_R}",
        f"  {_M}-f{_R}        {_G}Format: opus, m4a, mp3, webm (default from config){_R}",
        f"{_G}  Downloads are saved to {_M}~/.flow/downloads/{_R}",
        f"{_G}  Already downloaded songs are skipped.{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}download never gonna give you up{_R}",
        f"    {_G}download 2{_R}",
        f"    {_G}download never gonna{_R} {_M}-f mp3{_R}",
    ],
    "delete": [
        f"{_T}> delete{_R} {_M}<name | index>{_R}",
        f"{_G}  Delete a downloaded song from your library.{_R}",
        f"  {_M}<name>{_R}   {_G}Delete by song title{_R}",
        f"  {_M}<index>{_R}   {_G}Delete by index from last search results{_R}",
        f"{_G}  Asks for confirmation before deleting.{_R}",
        f"  {_G}Alias:{_R} {_M}dl-d{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}delete never gonna give you up{_R}",
        f"    {_G}dl-d 2{_R}",
    ],
    "savan": [
        f"{_T}> savan{_R} {_M}<query | index>{_R}",
        f"{_G}  Search and play a song from JioSaavn.{_R}",
        f"  {_M}<query>{_R}   {_G}Search JioSaavn and play the top result{_R}",
        f"  {_M}<index>{_R}   {_G}Play song by index from last savan-s results{_R}",
        f"  {_M}Flags:{_R} {_G}{_M}-bg{_R} {_G}background |{_R} {_M}-r{_R} {_G}repeat |{_R} {_M}-s{_R} {_G}shuffle{_R}",
        f"  {_G}Alias:{_R} {_M}svn{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}savan hello{_R}",
        f"    {_G}savan 2{_R}",
    ],
    "savan-s": [
        f"{_T}> savan-s{_R} {_M}<query>{_R}",
        f"{_G}  Search JioSaavn for tracks. Lists results with indices.{_R}",
        f"{_G}  Use the index with {_M}'savan <index>' {_G}to play a specific result.{_R}",
        f"  {_G}Alias:{_R} {_M}svn-s{_R}",
        f"  {_G}Example:{_R}",
        f"    {_G}savan-s daft punk{_R}",
    ],
    "radio": [
        f"{_T}> radio{_R} {_M}<song_name> [index]{_R}",
        f"{_G}  Generate a radio mix based on a reference song.{_R}",
        f"  {_M}<song_name>{_R}  {_G}Search and play a radio mix from YouTube{_R}",
        f"  {_M}[index]{_R}       {_G}Play a specific track from the last radio list{_R}",
        f"  {_M}Flags:{_R} {_G}{_M}-bg{_R} {_G}background |{_R} {_M}-d{_R} {_G}download{_R}",
        f"{_G}  Press Ctrl+C for next track, Ctrl+Q to quit. Alias:{_R} {_M}rd{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}radio daft punk{_R}",
        f"    {_G}radio 5{_R}",
    ],
    "switch": [
        f"{_T}> switch{_R}",
        f"{_G}  Switch to Offline mode.{_R}",
        f"{_G}  Requires an active internet connection.{_R}",
    ],
    "help": [
        f"{_T}> help{_R} {_M}[-i]{_R}",
        f"{_G}  Show this help message.{_R}",
        f"  {_M}-i{_R}     {_G}Show detailed usage for all commands.{_R}",
    ],
    "short": [
        f"{_T}> short{_R} {_M}[index] [new_command]{_R}",
        f"{_G}  View or edit command shortcuts.{_R}",
        f"{_G}  With no arguments, list all shortcuts.{_R}",
        f"  {_M}<index>{_R}          {_G}Show shortcut at that index{_R}",
        f"  {_M}<index> <value>{_R}  {_G}Update shortcut at index to new command{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}short{_R}",
        f"    {_G}short 3{_R}",
        f"    {_G}short 3 list{_R}",
    ],
    "exit": [
        f"{_T}> exit{_R}",
        f"{_G}  Exit Flow Music Player.{_R}",
        f"{_G}  Aliases:{_R} {_M}quit{_R}, {_M}q{_R}",
    ],
    "config": [
        f"{_T}> config{_R} {_M}<target> <value>{_R}",
        f"{_G}  Change settings. Use {_M}config help{_G} to see all targets.{_R}",
        f"  {_M}format{_R}     {_G}Default download format (opus, m4a, mp3, webm){_R}",
        f"  {_M}max_search{_R} {_G}Max YouTube search results (1-20, current: {_M}{config.MAX_SEARCH_RESULTS}{_G}){_R}",
        f"  {_M}max_radio{_R}  {_G}Max radio tracks (1-50, current: {_M}{config.MAX_RESULTS_RADIO}{_G}){_R}",
    ],
    "check": [
        f"{_T}> check{_R}",
        f"{_G}  Check all dependencies (ffmpeg, vlc, yt-dlp, psutil).{_R}",
        f"{_G}  Also available as: {_M}flow --check{_R}",
    ],
    "playlist": [
        f"{_T}> playlist{_R} {_M}<subcommand> [args]{_R}",
        f"{_G}  Manage playlists. Subcommands:{_R}",
        f"  {_M}create{_R} {_G}<name>{_R}          {_G}Create a new playlist{_R}",
        f"  {_M}delete{_R} {_G}<name>{_R}          {_G}Delete a playlist{_R}",
        f"  {_M}add{_R}    {_G}<name> <index>{_R}  {_G}Add a song by search index{_R}",
        f"  {_M}remove{_R} {_G}<name> <index>{_R}  {_G}Remove a song by index{_R}",
        f"  {_M}list{_R}   {_G}<name>{_R}          {_G}List songs in a playlist{_R}",
        f"  {_M}play{_R}   {_G}<name>{_R}          {_G}Play all songs in a playlist{_R}",
        f"  {_M}Flags:{_R} {_G}{_M}-bg{_R} {_G}background |{_R} {_M}-r{_R} {_G}repeat |{_R} {_M}-s{_R} {_G}shuffle{_R}",
        f"  {_G}Alias:{_R} {_M}plist{_R}",
    ],
    "export": [
        f"{_T}> export{_R}",
        f"{_G}  Backup ~/.flow config and data to ~/Downloads/flow_backup.zip{_R}",
    ],
    "stop": [
        f"{_T}> flow --stop{_R}",
        f"{_G}  Toggle stop/resume on the background VLC or web player.{_R}",
        f"{_G}  Use from shell: {_M}flow --stop{_R}",
    ],
}

OFFLINE_HELP = {
    "play": [
        f"{_T}> play{_R} {_B}<query | index | all | liked | album>{_R}",
        f"{_G}  Play a song from your local music library.{_R}",
        f"  {_B}<query>{_R}   {_G}Search and play matching song{_R}",
        f"  {_B}<index>{_R}   {_G}Play song by index from last search results{_R}",
        f"  {_B}all{_R}       {_G}Play all songs in the library{_R}",
        f"  {_B}liked{_R}     {_G}Play all liked songs{_R}",
        f"  {_B}<album>{_R}   {_G}Play all songs in a specific album{_R}",
        f"  {_B}Flags:{_R} {_G}{_B}-bg{_R} {_G}background |{_R} {_B}-r{_R} {_G}repeat |{_B}-s{_R} {_G}shuffle{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}play never gonna{_R}",
        f"    {_G}play 2{_R}",
        f"    {_G}play all{_R} {_B}-s{_R}",
        f"    {_G}play liked{_R}",
        f"    {_G}play Greatest Hits{_R}",
    ],
    "search": [
        f"{_T}> search{_R} {_B}<query>{_R}",
        f"{_G}  Search your local music library for matching songs.{_R}",
        f"{_G}  Lists results with indices for use with {_B}'play <index>'{_R}",
        f"  {_G}Example:{_R}",
        f"    {_G}search daft punk{_R}",
    ],
    "list": [
        f"{_T}> list{_R}",
        f"{_G}  List your entire music library.{_R}",
        f"{_G}  Shows Songs, Albums, and Liked Songs sections.{_R}",
    ],
    "like": [
        f"{_T}> like{_R}",
        f"{_G}  Like/unlike the currently playing song from offline mode.{_R}",
        f"{_G}  Liked songs are copied to {_B}~/.flow/downloads/liked songs/{_R}",
        f"{_G}  Use {_B}'play liked'{_G} to play all liked songs.{_R}",
    ],
    "radio": [
        f"{_T}> radio{_R}",
        f"{_G}  Radio mode: shuffles and loops the entire local library.{_R}",
        f"  {_B}Ctrl+C{_R}  {_G}Skip to the next song{_R}",
        f"  {_B}Ctrl+Q{_R}  {_G}Exit radio mode{_R}",
        f"  {_B}Ctrl+P{_R}  {_G}Toggle pause{_R}",
        f"  {_B}Flags:{_R} {_G}{_B}-bg{_R} {_G}background{_R}",
        f"  {_G}Alias:{_R} {_B}rd{_R}",
    ],
    "playlist": [
        f"{_T}> playlist{_R} {_B}<subcommand> [args]{_R}",
        f"{_G}  Manage playlists. Subcommands:{_R}",
        f"  {_B}create{_R} {_G}<name>{_R}          {_G}Create a new playlist{_R}",
        f"  {_B}delete{_R} {_G}<name>{_R}          {_G}Delete a playlist{_R}",
        f"  {_B}add{_R}    {_G}<name> <index>{_R}  {_G}Add a song by index from last search{_R}",
        f"  {_B}remove{_R} {_G}<name> <index>{_R}  {_G}Remove a song by index{_R}",
        f"  {_B}list{_R}   {_G}<name>{_R}          {_G}List songs in a playlist{_R}",
        f"  {_B}play{_R}   {_G}<name>{_R}          {_G}Play all songs in a playlist{_R}",
        f"  {_B}Flags:{_R} {_G}{_B}-bg{_R} {_G}background |{_R} {_B}-r{_R} {_G}repeat |{_B}-s{_R} {_G}shuffle{_R}",
        f"  {_G}Alias:{_R} {_B}plist{_R}",
    ],
    "switch": [
        f"{_T}> switch{_R}",
        f"{_G}  Switch to Online mode.{_R}",
        f"{_G}  Requires an active internet connection.{_R}",
    ],
    "help": [
        f"{_T}> help{_R} {_B}[-i]{_R}",
        f"{_G}  Show this help message.{_R}",
        f"  {_B}-i{_R}     {_G}Show detailed usage for all commands.{_R}",
    ],
    "short": [
        f"{_T}> short{_R} {_B}[index] [new_command]{_R}",
        f"{_G}  View or edit command shortcuts.{_R}",
        f"{_G}  With no arguments, list all shortcuts.{_R}",
        f"  {_B}<index>{_R}          {_G}Show shortcut at that index{_R}",
        f"  {_B}<index> <value>{_R}  {_G}Update shortcut at index to new command{_R}",
        f"  {_G}Examples:{_R}",
        f"    {_G}short{_R}",
        f"    {_G}short 3{_R}",
        f"    {_G}short 3 list{_R}",
    ],
    "exit": [
        f"{_T}> exit{_R}",
        f"{_G}  Exit Flow Music Player.{_R}",
        f"{_G}  Aliases:{_R} {_B}quit{_R}, {_B}q{_R}",
    ],
    "config": [
        f"{_T}> config{_R} {_B}<target> <value>{_R}",
        f"{_G}  Change settings. Use {_B}config help{_G} to see all targets.{_R}",
        f"  {_B}format{_R}     {_G}Default download format (opus, m4a, mp3, webm){_R}",
        f"  {_B}max_search{_R} {_G}Max YouTube search results (1-20, current: {_B}{config.MAX_SEARCH_RESULTS}{_G}){_R}",
        f"  {_B}max_radio{_R}  {_G}Max radio tracks (1-50, current: {_B}{config.MAX_RESULTS_RADIO}{_G}){_R}",
    ],
    "check": [
        f"{_T}> check{_R}",
        f"{_G}  Check all dependencies (ffmpeg, vlc, yt-dlp, psutil).{_R}",
        f"{_G}  Also available as: {_B}flow --check{_R}",
    ],
    "export": [
        f"{_T}> export{_R}",
        f"{_G}  Backup ~/.flow config and data to ~/Downloads/flow_backup.zip{_R}",
    ],
    "stop": [
        f"{_T}> flow --stop{_R}",
        f"{_G}  Toggle stop/resume on the background VLC or web player.{_R}",
        f"{_G}  Use from shell: {_B}flow --stop{_R}",
    ],
}
